### ISSUE TITLE
v1 suggestions

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cq-source-simple-analytics#3]
Great work on the plugin @hermanschaaf 🚀 

I don't have much to comment, only:
1. For the first version maybe we can simplify and only have period (instead of multiple way to define a time span)
2. For the first version maybe no support incremental syncs until the plugin gets traction
3. I borrowed some of your testing code, but took a bit of a different approach with the data:
https://github.com/cloudquery/cq-source-plaid/blob/97f78bdd8600e137379ec727250957250339c10a/resources/wallets_test.go#L22
https://github.com/cloudquery/cq-source-plaid/blob/97f78bdd8600e137379ec727250957250339c10a/resources/testing.go#L15
that way we don't need to update the test data if the responses change (e.g. on SDK update).

All the suggestions are pretty minor in my opinion

**Comment by hermanschaaf** [comment]
Thanks @erezrokah !

1. I added `period` later as a convenience function. The underlying API actually only supports `start` and `end`. It does complicate things a little bit, but I think it's worth it and it's up to users whether they want to use it or not.
2. Incremental syncs: yeah, though this kind of endpoint is the ideal case for incremental syncing, it's already written now, and it's an optional feature users don't have to use if they don't want to. I think it's good that we turn it off by default though, and add some more docs: https://github.com/cloudquery/cq-source-simple-analytics/pull/4
3. Thanks! Nice idea, I think I'll do that but keep the testdata responses for the internal SDK tests.

**Comment by erezrokah** [comment]
Cool, thanks for following up! I'll close this issue as resolved
